#
# Docker Compose Configuration, https://docs.docker.com/compose/.
#

version: '3.3'

services:
    app-local-db:
        container_name: app-local-db
        build: ./db
        ports:
            - "49161:1521"
        restart: always
        volumes:
            - app-local-db-data:/var/lib/mysql
        environment:
            ORACLE_ALLOW_REMOTE: "true"

    app-local-web:
        depends_on:
            - app-local-db
        container_name: app-local-web
        build: ./web
        ports:
            - "${port_for_http}:80"
            - "${port_for_https}:443"
        restart: always
        volumes:
          - ${your_laravel_project_repo}:/app/source
        command: bash /where_ever_you_place_this_code_in_the_container/start.sh
volumes:
    app-local-db-data:
